#!/usr/bin/env node
/**
 * Migration runner for the project's SQLite database.
 *
 * Applies the SQL files generated by `drizzle-kit generate`, keeping the same
 * bookkeeping table Drizzle uses (`__drizzle_migrations`).
 *
 * - Local / self-hosted: Node's built-in `node:sqlite` over a file.
 * - Hosted (Vercel + Turso/libSQL): set `TURSO_DATABASE_URL` (+ token) and the
 *   very same migrations are applied to the hosted database.
 *
 * Usage: npm run db:migrate
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const journalPath = join(root, "drizzle", "meta", "_journal.json");
const dbPath = process.env.DATABASE_PATH ?? join(root, "data", "getpadel.db");

const journal = JSON.parse(readFileSync(journalPath, "utf8"));

const libsqlUrl = process.env.TURSO_DATABASE_URL ?? process.env.LIBSQL_URL;

async function migrateHosted() {
  const { createClient } = await import("@libsql/client");
  const authToken =
    process.env.TURSO_AUTH_TOKEN ?? process.env.LIBSQL_AUTH_TOKEN ?? undefined;
  const client = createClient({ url: libsqlUrl, ...(authToken ? { authToken } : {}) });

  await client.execute(`
    CREATE TABLE IF NOT EXISTS __drizzle_migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      hash TEXT NOT NULL,
      created_at INTEGER NOT NULL
    );
  `);

  const appliedRows = await client.execute("SELECT hash FROM __drizzle_migrations");
  const applied = new Set(appliedRows.rows.map((row) => String(row.hash)));

  let count = 0;
  for (const entry of journal.entries) {
    const sqlPath = join(root, "drizzle", `${entry.tag}.sql`);
    const sqlText = readFileSync(sqlPath, "utf8");
    const hash = createHash("sha256").update(sqlText).digest("hex");
    if (applied.has(hash)) continue;

    const statements = sqlText
      .split("--> statement-breakpoint")
      .map((s) => s.trim())
      .filter(Boolean);

    try {
      await client.batch(
        [
          ...statements,
          {
            sql: "INSERT INTO __drizzle_migrations (hash, created_at) VALUES (?, ?)",
            args: [hash, entry.when],
          },
        ],
        "write"
      );
      count += 1;
      console.log(`✓ applied ${entry.tag}`);
    } catch (error) {
      console.error(`✗ failed ${entry.tag}:`, error.message);
      process.exit(1);
    }
  }

  const tables = await client.execute(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '__drizzle%' ORDER BY name"
  );

  console.log(
    count === 0 ? "Database already up to date." : `Applied ${count} migration(s).`
  );
  console.log(`Tables: ${tables.rows.map((row) => String(row.name)).join(", ")}`);
  console.log(`Database: ${libsqlUrl}`);
}

if (libsqlUrl) {
  await migrateHosted();
  process.exit(0);
}

mkdirSync(dirname(dbPath), { recursive: true });
const db = new DatabaseSync(dbPath);

db.exec(`
  CREATE TABLE IF NOT EXISTS __drizzle_migrations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash TEXT NOT NULL,
    created_at INTEGER NOT NULL
  );
`);

const appliedRows = db
  .prepare("SELECT hash FROM __drizzle_migrations")
  .all()
  .map((row) => row.hash);
const applied = new Set(appliedRows);

let count = 0;
for (const entry of journal.entries) {
  const sqlPath = join(root, "drizzle", `${entry.tag}.sql`);
  const sqlText = readFileSync(sqlPath, "utf8");
  const hash = createHash("sha256").update(sqlText).digest("hex");

  if (applied.has(hash)) continue;

  const statements = sqlText
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter(Boolean);

  db.exec("BEGIN");
  try {
    for (const statement of statements) db.exec(statement);
    db.prepare(
      "INSERT INTO __drizzle_migrations (hash, created_at) VALUES (?, ?)"
    ).run(hash, entry.when);
    db.exec("COMMIT");
    count += 1;
    console.log(`✓ applied ${entry.tag}`);
  } catch (error) {
    db.exec("ROLLBACK");
    console.error(`✗ failed ${entry.tag}:`, error.message);
    process.exit(1);
  }
}

const tables = db
  .prepare(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '__drizzle%' ORDER BY name"
  )
  .all()
  .map((row) => row.name);

console.log(
  count === 0
    ? "Database already up to date."
    : `Applied ${count} migration(s).`
);
console.log(`Tables: ${tables.join(", ")}`);
console.log(`Database: ${dbPath}`);
