#!/usr/bin/env node
/**
 * Migration runner for the project's SQLite database.
 *
 * Applies the SQL files generated by `drizzle-kit generate` using Node's
 * built-in `node:sqlite` (no native dependencies), keeping the same
 * bookkeeping table Drizzle uses (`__drizzle_migrations`).
 *
 * Usage: npm run db:migrate
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { DatabaseSync } from "node:sqlite";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const journalPath = join(root, "drizzle", "meta", "_journal.json");
const dbPath = process.env.DATABASE_PATH ?? join(root, "data", "getpadel.db");

const journal = JSON.parse(readFileSync(journalPath, "utf8"));

mkdirSync(dirname(dbPath), { recursive: true });
const db = new DatabaseSync(dbPath);

db.exec(`
  CREATE TABLE IF NOT EXISTS __drizzle_migrations (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    hash TEXT NOT NULL,
    created_at INTEGER NOT NULL
  );
`);

const appliedRows = db
  .prepare("SELECT hash FROM __drizzle_migrations")
  .all()
  .map((row) => row.hash);
const applied = new Set(appliedRows);

let count = 0;
for (const entry of journal.entries) {
  const sqlPath = join(root, "drizzle", `${entry.tag}.sql`);
  const sqlText = readFileSync(sqlPath, "utf8");
  const hash = createHash("sha256").update(sqlText).digest("hex");

  if (applied.has(hash)) continue;

  const statements = sqlText
    .split("--> statement-breakpoint")
    .map((s) => s.trim())
    .filter(Boolean);

  db.exec("BEGIN");
  try {
    for (const statement of statements) db.exec(statement);
    db.prepare(
      "INSERT INTO __drizzle_migrations (hash, created_at) VALUES (?, ?)"
    ).run(hash, entry.when);
    db.exec("COMMIT");
    count += 1;
    console.log(`✓ applied ${entry.tag}`);
  } catch (error) {
    db.exec("ROLLBACK");
    console.error(`✗ failed ${entry.tag}:`, error.message);
    process.exit(1);
  }
}

const tables = db
  .prepare(
    "SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' AND name NOT LIKE '__drizzle%' ORDER BY name"
  )
  .all()
  .map((row) => row.name);

console.log(
  count === 0
    ? "Database already up to date."
    : `Applied ${count} migration(s).`
);
console.log(`Tables: ${tables.join(", ")}`);
console.log(`Database: ${dbPath}`);
