/**
 * Seed the SQLite database with the venue, its two courts, and 30 days of
 * hourly slot availability — generated by the same mock engine the UI uses
 * (`src/data/slots.ts`), so UI and DB stay consistent until the AYO
 * integration lands.
 *
 * Idempotent: re-running upserts by primary key and refreshes slot statuses.
 *
 * Usage: npm run db:seed
 */
import { eq, ne, sql } from "drizzle-orm";
import { db, schema } from "../src/db/index";
import { courts as courtData } from "../src/data/courts";
import { blogPosts as blogData } from "../src/data/blog-posts";
import { events as eventData } from "../src/data/events";
import { galleryPhotos as galleryData } from "../src/data/gallery";
import { faqItems } from "../src/data/faq";
import { facilities as facilityData } from "../src/data/facilities";
import { testimonials as testimonialData } from "../src/data/testimonials";
import {
  FREE_TRIAL_REGISTRATION_URL,
  programs as programData,
} from "../src/data/programs";
import { FIRST_HOUR, LAST_HOUR } from "../src/data/pricing";
import { getSlotPrice } from "../src/data/pricing";
import { archivedPromos, promos as runningPromos } from "../src/data/promos";
import { site } from "../src/data/site";
import { parseIDR } from "../src/lib/format";

const VENUE_ID = "get-padel-jakarta";

function localImage(courtId: string): string {
  return `/images/${courtId}.jpg`;
}

async function seedVenue() {
  await db
    .insert(schema.venues)
    .values({
      id: VENUE_ID,
      name: site.name,
      tagline: site.tagline,
      addressStreet: site.address.street,
      addressDistrict: site.address.district,
      addressCity: site.address.city,
      plusCode: site.address.plusCode,
      latitude: site.address.coordinates.lat,
      longitude: site.address.coordinates.lng,
      courtOpenHour: 6,
      courtCloseHour: 22,
      cafeOpenHour: 7,
      cafeCloseHour: 22,
      sessionMinutes: 60,
      ratingGoogle: site.ratings.google.score,
      ratingGoogleCount: site.ratings.google.count,
      ratingAyo: site.ratings.ayo.score,
      ratingAyoCount: site.ratings.ayo.count,
      ratingCleanliness: site.ratings.sub.cleanliness,
      ratingCourtCondition: site.ratings.sub.court,
      ratingCommunication: site.ratings.sub.communication,
      whatsapp: site.contact.whatsapp,
      emailEvent: site.contact.emailEvent,
      emailCommercial: site.contact.emailCommercial,
      instagramUrl: site.links.instagram,
      tiktokUrl: site.links.tiktok,
      cafeInstagramUrl: site.links.cafeInstagram,
      bookingUrl: site.links.ayo,
      mapsUrl: site.links.maps,
      linktreeUrl: site.links.linktree,
      updatedAt: new Date(),
    })
    .onConflictDoUpdate({
      target: schema.venues.id,
      set: {
        name: site.name,
        tagline: site.tagline,
        addressStreet: site.address.street,
        addressDistrict: site.address.district,
        addressCity: site.address.city,
        plusCode: site.address.plusCode,
        latitude: site.address.coordinates.lat,
        longitude: site.address.coordinates.lng,
        ratingGoogle: site.ratings.google.score,
        ratingGoogleCount: site.ratings.google.count,
        ratingAyo: site.ratings.ayo.score,
        ratingAyoCount: site.ratings.ayo.count,
        ratingCleanliness: site.ratings.sub.cleanliness,
        ratingCourtCondition: site.ratings.sub.court,
        ratingCommunication: site.ratings.sub.communication,
        whatsapp: site.contact.whatsapp,
        updatedAt: new Date(),
      },
    });
  console.log(`✓ venue ${VENUE_ID}`);
}

async function seedCourts() {
  for (const [index, court] of courtData.entries()) {
    const values = {
      id: court.id,
      venueId: VENUE_ID,
      name: court.name,
      indoor: court.indoor,
      surface: court.surface,
      sessionMinutes: court.sessionMinutes,
      descriptionEn: court.description,
      imageUrl: localImage(court.id),
      sortOrder: index + 1,
    };
    await db
      .insert(schema.courts)
      .values(values)
      .onConflictDoUpdate({
        target: schema.courts.id,
        set: {
          name: values.name,
          surface: values.surface,
          sessionMinutes: values.sessionMinutes,
          descriptionEn: values.descriptionEn,
          imageUrl: values.imageUrl,
          sortOrder: values.sortOrder,
        },
      });
  }
  console.log(`✓ courts ${courtData.map((court) => court.id).join(", ")}`);
}

async function seedFacilities() {
  for (const [index, facility] of facilityData.entries()) {
    const values = {
      id: facility.id,
      venueId: VENUE_ID,
      titleId: facility.title.id,
      titleEn: facility.title.en,
      detailId: facility.detail?.id ?? null,
      detailEn: facility.detail?.en ?? null,
      icon: facility.icon,
      official: facility.official,
      sortOrder: index + 1,
    };
    await db
      .insert(schema.facilities)
      .values(values)
      .onConflictDoUpdate({
        target: schema.facilities.id,
        set: {
          titleId: values.titleId,
          titleEn: values.titleEn,
          detailId: values.detailId,
          detailEn: values.detailEn,
          icon: values.icon,
          official: values.official,
          sortOrder: values.sortOrder,
        },
      });
  }
  const officialCount = facilityData.filter((facility) => facility.official).length;
  console.log(
    `✓ facilities ${facilityData.length} rows (${officialCount} official + ${facilityData.length - officialCount} extras)`
  );
}

const PROGRAM_KINDS: Record<string, "private" | "multi_session" | "junior" | "free_trial"> = {
  "private-coaching": "private",
  "multi-session-coaching": "multi_session",
  "junior-class": "junior",
  "free-trial": "free_trial",
};

async function seedPrograms() {
  for (const [index, program] of programData.entries()) {
    const kind = PROGRAM_KINDS[program.id];
    if (!kind) continue;
    const values = {
      id: program.id,
      venueId: VENUE_ID,
      kind,
      titleId: program.title.id,
      titleEn: program.title.en,
      descriptionId: program.description.id,
      descriptionEn: program.description.en,
      highlights: JSON.stringify(program.highlights),
      priceNoteId: program.priceNote?.id ?? null,
      priceNoteEn: program.priceNote?.en ?? null,
      ctaKind:
        program.cta === "form"
          ? ("form" as const)
          : program.cta === "ayo"
            ? ("ayo" as const)
            : ("whatsapp" as const),
      registrationUrl:
        program.cta === "form" ? FREE_TRIAL_REGISTRATION_URL : null,
      isActive: true,
      sortOrder: index + 1,
      updatedAt: new Date(),
    };
    await db
      .insert(schema.coachingPrograms)
      .values(values)
      .onConflictDoUpdate({
        target: schema.coachingPrograms.id,
        set: {
          kind: values.kind,
          titleId: values.titleId,
          titleEn: values.titleEn,
          descriptionId: values.descriptionId,
          descriptionEn: values.descriptionEn,
          highlights: values.highlights,
          priceNoteId: values.priceNoteId,
          priceNoteEn: values.priceNoteEn,
          ctaKind: values.ctaKind,
          registrationUrl: values.registrationUrl,
          isActive: values.isActive,
          sortOrder: values.sortOrder,
          updatedAt: values.updatedAt,
        },
      });

    for (const [tierIndex, tier] of (program.priceRows ?? []).entries()) {
      const tierValues = {
        id: `${program.id}:${tierIndex + 1}`,
        programId: program.id,
        labelId: tier.label.id,
        labelEn: tier.label.en,
        priceIdr: parseIDR(tier.value),
        sortOrder: tierIndex + 1,
      };
      await db
        .insert(schema.coachingProgramTiers)
        .values(tierValues)
        .onConflictDoUpdate({
          target: schema.coachingProgramTiers.id,
          set: {
            labelId: tierValues.labelId,
            labelEn: tierValues.labelEn,
            priceIdr: tierValues.priceIdr,
            sortOrder: tierValues.sortOrder,
          },
        });
    }
  }
  const tierCount = programData.reduce(
    (total, program) => total + (program.priceRows?.length ?? 0),
    0
  );
  console.log(
    `✓ coaching_programs ${programData.length} rows · tiers ${tierCount} rows`
  );
}

const EVENT_KINDS: Record<
  string,
  "tournament" | "social" | "class" | "community"
> = {
  "chasing-sunset": "tournament",
  "junior-summer-class": "class",
  "jamu-day": "social",
  "hari-kartini": "social",
  "fortune-cookie-day": "social",
};

async function seedEvents() {
  for (const [index, event] of eventData.entries()) {
    const values = {
      id: event.id,
      venueId: VENUE_ID,
      kind: EVENT_KINDS[event.id] ?? ("community" as const),
      titleId: event.title.id,
      titleEn: event.title.en,
      descriptionId: event.description.id,
      descriptionEn: event.description.en,
      periodId: event.period.id,
      periodEn: event.period.en,
      startsAt: event.startsAt ? new Date(event.startsAt) : null,
      isActive: true,
      sortOrder: index + 1,
      updatedAt: new Date(),
    };
    await db
      .insert(schema.events)
      .values(values)
      .onConflictDoUpdate({
        target: schema.events.id,
        set: {
          kind: values.kind,
          titleId: values.titleId,
          titleEn: values.titleEn,
          descriptionId: values.descriptionId,
          descriptionEn: values.descriptionEn,
          periodId: values.periodId,
          periodEn: values.periodEn,
          startsAt: values.startsAt,
          isActive: values.isActive,
          sortOrder: values.sortOrder,
          updatedAt: values.updatedAt,
        },
      });
  }
  console.log(`✓ events ${eventData.length} rows`);
}

async function seedFaqs() {
  for (const [index, faq] of faqItems.entries()) {
    const values = {
      id: faq.id,
      venueId: VENUE_ID,
      questionId: faq.question.id,
      questionEn: faq.question.en,
      answerId: faq.answer.id,
      answerEn: faq.answer.en,
      isActive: true,
      sortOrder: index + 1,
      updatedAt: new Date(),
    };
    await db
      .insert(schema.faqs)
      .values(values)
      .onConflictDoUpdate({
        target: schema.faqs.id,
        set: {
          questionId: values.questionId,
          questionEn: values.questionEn,
          answerId: values.answerId,
          answerEn: values.answerEn,
          isActive: values.isActive,
          sortOrder: values.sortOrder,
          updatedAt: values.updatedAt,
        },
      });
  }
  console.log(`✓ faqs ${faqItems.length} rows (bilingual)`);
}

async function seedTestimonials() {
  for (const [index, item] of testimonialData.entries()) {
    const values = {
      id: item.id,
      venueId: VENUE_ID,
      author: item.author,
      source: item.source,
      rating: item.rating,
      periodId: item.period.id,
      periodEn: item.period.en,
      quoteId: item.quote.id,
      quoteEn: item.quote.en,
      isActive: true,
      sortOrder: index + 1,
      updatedAt: new Date(),
    };
    await db
      .insert(schema.testimonials)
      .values(values)
      .onConflictDoUpdate({
        target: schema.testimonials.id,
        set: {
          author: values.author,
          source: values.source,
          rating: values.rating,
          periodId: values.periodId,
          periodEn: values.periodEn,
          quoteId: values.quoteId,
          quoteEn: values.quoteEn,
          isActive: values.isActive,
          sortOrder: values.sortOrder,
          updatedAt: values.updatedAt,
        },
      });
  }
  console.log(`✓ testimonials ${testimonialData.length} rows`);
}

async function seedGallery() {
  for (const [index, photo] of galleryData.entries()) {
    const values = {
      id: photo.id,
      venueId: VENUE_ID,
      src: photo.src,
      altId: photo.alt.id,
      altEn: photo.alt.en,
      isActive: true,
      sortOrder: index + 1,
      updatedAt: new Date(),
    };
    await db
      .insert(schema.galleryPhotos)
      .values(values)
      .onConflictDoUpdate({
        target: schema.galleryPhotos.id,
        set: {
          src: values.src,
          altId: values.altId,
          altEn: values.altEn,
          isActive: values.isActive,
          sortOrder: values.sortOrder,
          updatedAt: values.updatedAt,
        },
      });
  }
  // Remove photos that are no longer part of the seeded set (keeps the
  // gallery duplicate-free after content changes).
  const keep = new Set(galleryData.map((photo) => photo.id));
  const existing = await db
    .select({ id: schema.galleryPhotos.id })
    .from(schema.galleryPhotos);
  for (const row of existing) {
    if (!keep.has(row.id)) {
      await db
        .delete(schema.galleryPhotos)
        .where(eq(schema.galleryPhotos.id, row.id));
    }
  }
  console.log(`✓ gallery_photos ${galleryData.length} rows`);
}

async function seedBlogPosts() {
  for (const post of blogData) {
    const values = {
      id: post.slug,
      venueId: VENUE_ID,
      slug: post.slug,
      titleId: post.title.id,
      titleEn: post.title.en,
      excerptId: post.excerpt.id,
      excerptEn: post.excerpt.en,
      bodyId: JSON.stringify(post.body.map((paragraph) => paragraph.id)),
      bodyEn: JSON.stringify(post.body.map((paragraph) => paragraph.en)),
      tagId: post.tag.id,
      tagEn: post.tag.en,
      coverUrl: post.cover,
      readMinutes: post.readMinutes,
      publishedAt: new Date(post.date),
      isActive: true,
      updatedAt: new Date(),
    };
    await db
      .insert(schema.blogPosts)
      .values(values)
      .onConflictDoUpdate({
        target: schema.blogPosts.id,
        set: {
          slug: values.slug,
          titleId: values.titleId,
          titleEn: values.titleEn,
          excerptId: values.excerptId,
          excerptEn: values.excerptEn,
          bodyId: values.bodyId,
          bodyEn: values.bodyEn,
          tagId: values.tagId,
          tagEn: values.tagEn,
          coverUrl: values.coverUrl,
          readMinutes: values.readMinutes,
          publishedAt: values.publishedAt,
          isActive: values.isActive,
          updatedAt: values.updatedAt,
        },
      });
  }
  console.log(`✓ blog_posts ${blogData.length} rows`);
}

/**
 * The schedule is NEVER seeded from fabricated data. Legacy mock rows (from
 * the pre-AYO prototype) are removed so only official AYO syncs remain.
 */
async function purgeMockSlots() {
  const result = await db
    .delete(schema.scheduleSlots)
    .where(ne(schema.scheduleSlots.source, "ayo"));
  console.log("✓ schedule_slots pruned to official AYO rows");
  return result;
}

/** Representative dates per day type (Monday & Saturday). */
const SAMPLE_DATE: Record<"weekday" | "weekend", string> = {
  weekday: "2026-09-21",
  weekend: "2026-09-26",
};

async function seedPricing() {
  const rows: (typeof schema.pricingRules.$inferInsert)[] = [];
  for (const dayType of ["weekday", "weekend"] as const) {
    for (let hour = FIRST_HOUR; hour <= LAST_HOUR; hour++) {
      const { price, strike } = getSlotPrice(SAMPLE_DATE[dayType], hour);
      rows.push({
        id: `${dayType}:${hour}`,
        venueId: VENUE_ID,
        dayType,
        hour,
        price,
        strikePrice: strike,
        isPeak: dayType === "weekend" ? hour >= 7 : hour >= 18,
      });
    }
  }

  await db
    .insert(schema.pricingRules)
    .values(rows)
    .onConflictDoUpdate({
      target: schema.pricingRules.id,
      set: {
        price: sql`excluded.price`,
        strikePrice: sql`excluded.strike_price`,
        isPeak: sql`excluded.is_peak`,
      },
    });
  console.log(`✓ pricing_rules ${rows.length} rows (weekday + weekend × 16 hours)`);
}

async function seedPromos() {
  const all = [...runningPromos, ...archivedPromos];
  const rows: (typeof schema.promos.$inferInsert)[] = all.map(
    (promo, index) => ({
      id: promo.id,
      venueId: VENUE_ID,
      titleId: promo.title.id,
      titleEn: promo.title.en,
      code: null,
      periodId: promo.period.id,
      periodEn: promo.period.en,
      detailId: promo.detail.id,
      detailEn: promo.detail.en,
      source: promo.source ?? null,
      linkUrl: promo.link ?? null,
      reference: promo.reference ?? null,
      posterUrl: promo.poster ?? null,
      startsOn: promo.startsOn ?? null,
      endsOn: promo.endsOn ?? null,
      isActive: !promo.archived,
      sortOrder: index,
      updatedAt: new Date(),
    })
  );

  for (const row of rows) {
    await db
      .insert(schema.promos)
      .values(row)
      .onConflictDoUpdate({
        target: schema.promos.id,
        set: {
          titleId: sql`excluded.title_id`,
          titleEn: sql`excluded.title_en`,
          periodId: sql`excluded.period_id`,
          periodEn: sql`excluded.period_en`,
          detailId: sql`excluded.detail_id`,
          detailEn: sql`excluded.detail_en`,
          source: sql`excluded.source`,
          linkUrl: sql`excluded.link_url`,
          reference: sql`excluded.reference`,
          posterUrl: sql`excluded.poster_url`,
          startsOn: sql`excluded.starts_on`,
          endsOn: sql`excluded.ends_on`,
          isActive: sql`excluded.is_active`,
          sortOrder: sql`excluded.sort_order`,
          updatedAt: sql`excluded.updated_at`,
        },
      });
  }
  console.log(
    `✓ promos ${rows.length} rows (${runningPromos.length} running + ${archivedPromos.length} archived)`
  );
}

async function main() {
  await seedVenue();
  await seedCourts();
  await seedFacilities();
  await seedPrograms();
  await seedEvents();
  await seedFaqs();
  await seedTestimonials();
  await seedGallery();
  await seedBlogPosts();
  await purgeMockSlots();
  await seedPricing();
  await seedPromos();
  console.log("Seed complete.");
}

main().catch((error) => {
  console.error("Seed failed:", error);
  process.exit(1);
});
